FROM alpine:3.15 AS compile

RUN apk add build-base

WORKDIR /root
COPY ["upload_runtime.c", "upload_runtime.h", "wait_for_exec.c", \
      "wait_for_exec.h", "consts.h", \
      "/root/"]

# In wait-for-exec mode, upload_runtime won't run as the dynamic linker, so we could go with glibc, but sticking with musl is fine
RUN gcc -static-pie -s upload_runtime.c wait_for_exec.c -o /upload_runtime

# -------------------------------- #

FROM ubuntu:18.04

RUN apt update && apt install -y curl 

COPY --from=compile /upload_runtime /upload_runtime
# Allow upload_runtime to create a binary pointing to /proc/self/exe
RUN chmod ugo+rwx /bin 

# run upload_runtime in wait_for_exec mode
ENTRYPOINT ["/upload_runtime", "-e"]
CMD ["127.0.0.1"] # default address
