FROM gcc:9.4.0 AS compile

WORKDIR /root
COPY ["upload_runtime.c", "upload_runtime.h", "wait_for_exec.c", \
      "wait_for_exec.h", "consts.h", \
      "/root/"]

RUN gcc -static -s upload_runtime.c wait_for_exec.c -o /upload_runtime

# -------------------------------- #

FROM ubuntu:18.04

RUN apt update && apt install -y curl 

COPY --from=compile /upload_runtime /upload_runtime

# run upload_runtime in wait_for_exec mode
ENTRYPOINT ["/upload_runtime", "-e"]
CMD ["127.0.0.1"] # default address
